//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.29 at 03:13:27 PM EET 
//


package ua.nure.it.xml.entity.place;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import ua.nure.it.xml.entity.datatypes.AddressType;
import ua.nure.it.xml.entity.datatypes.CoordinateType;
import ua.nure.it.xml.entity.datatypes.PriceDetail;
import ua.nure.it.xml.entity.datatypes.SeasonalityType;


/**
 * <p>Java class for Place complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Place"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://it.nure.ua/xml/entity/dataTypes}IDType"/&gt;
 *         &lt;element name="Name" type="{http://it.nure.ua/xml/entity/dataTypes}Name"/&gt;
 *         &lt;element name="Description" type="{http://it.nure.ua/xml/entity/dataTypes}DescriptionType"/&gt;
 *         &lt;element name="Type"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Beach"/&gt;
 *               &lt;enumeration value="Mountain"/&gt;
 *               &lt;enumeration value="City"/&gt;
 *               &lt;enumeration value="Excursion"/&gt;
 *               &lt;enumeration value="Active"/&gt;
 *               &lt;enumeration value="Nature"/&gt;
 *               &lt;enumeration value="Cultural"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Address" type="{http://it.nure.ua/xml/entity/dataTypes}AddressType" minOccurs="0"/&gt;
 *         &lt;element name="Coordinate" type="{http://it.nure.ua/xml/entity/dataTypes}CoordinateType"/&gt;
 *         &lt;element name="VisitTime" type="{http://it.nure.ua/xml/entity/dataTypes}DiapasonTime" minOccurs="0"/&gt;
 *         &lt;element name="EntranceFee" type="{http://it.nure.ua/xml/entity/dataTypes}PriceDetail" minOccurs="0"/&gt;
 *         &lt;element name="Photos" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Photo" type="{http://it.nure.ua/xml/entity/dataTypes}Photo" maxOccurs="10" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Seasonality" type="{http://it.nure.ua/xml/entity/dataTypes}SeasonalityType"/&gt;
 *         &lt;element name="Tags" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isRecommended" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="rating" default="0"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;minInclusive value="0"/&gt;
 *             &lt;maxInclusive value="5"/&gt;
 *             &lt;fractionDigits value="1"/&gt;
 *             &lt;totalDigits value="2"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Place", propOrder = {
    "id",
    "name",
    "description",
    "type",
    "address",
    "coordinate",
    "visitTime",
    "entranceFee",
    "photos",
    "seasonality",
    "tags"
})
public class Place {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "Address")
    protected AddressType address;
    @XmlElement(name = "Coordinate", required = true)
    protected CoordinateType coordinate;
    @XmlElement(name = "VisitTime")
    protected String visitTime;
    @XmlElement(name = "EntranceFee")
    protected PriceDetail entranceFee;
    @XmlElement(name = "Photos")
    protected Place.Photos photos;
    @XmlElement(name = "Seasonality", required = true)
    @XmlSchemaType(name = "string")
    protected SeasonalityType seasonality;
    @XmlElement(name = "Tags")
    protected Place.Tags tags;
    @XmlAttribute(name = "isRecommended", required = true)
    protected boolean isRecommended;
    @XmlAttribute(name = "rating")
    protected BigDecimal rating;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the coordinate property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateType }
     *     
     */
    public CoordinateType getCoordinate() {
        return coordinate;
    }

    /**
     * Sets the value of the coordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateType }
     *     
     */
    public void setCoordinate(CoordinateType value) {
        this.coordinate = value;
    }

    /**
     * Gets the value of the visitTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitTime() {
        return visitTime;
    }

    /**
     * Sets the value of the visitTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitTime(String value) {
        this.visitTime = value;
    }

    /**
     * Gets the value of the entranceFee property.
     * 
     * @return
     *     possible object is
     *     {@link PriceDetail }
     *     
     */
    public PriceDetail getEntranceFee() {
        return entranceFee;
    }

    /**
     * Sets the value of the entranceFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceDetail }
     *     
     */
    public void setEntranceFee(PriceDetail value) {
        this.entranceFee = value;
    }

    /**
     * Gets the value of the photos property.
     * 
     * @return
     *     possible object is
     *     {@link Place.Photos }
     *     
     */
    public Place.Photos getPhotos() {
        return photos;
    }

    /**
     * Sets the value of the photos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Place.Photos }
     *     
     */
    public void setPhotos(Place.Photos value) {
        this.photos = value;
    }

    /**
     * Gets the value of the seasonality property.
     * 
     * @return
     *     possible object is
     *     {@link SeasonalityType }
     *     
     */
    public SeasonalityType getSeasonality() {
        return seasonality;
    }

    /**
     * Sets the value of the seasonality property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeasonalityType }
     *     
     */
    public void setSeasonality(SeasonalityType value) {
        this.seasonality = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link Place.Tags }
     *     
     */
    public Place.Tags getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link Place.Tags }
     *     
     */
    public void setTags(Place.Tags value) {
        this.tags = value;
    }

    /**
     * Gets the value of the isRecommended property.
     * 
     */
    public boolean isIsRecommended() {
        return isRecommended;
    }

    /**
     * Sets the value of the isRecommended property.
     * 
     */
    public void setIsRecommended(boolean value) {
        this.isRecommended = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRating() {
        if (rating == null) {
            return new BigDecimal("0");
        } else {
            return rating;
        }
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRating(BigDecimal value) {
        this.rating = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Photo" type="{http://it.nure.ua/xml/entity/dataTypes}Photo" maxOccurs="10" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "photo"
    })
    public static class Photos {

        @XmlElement(name = "Photo")
        protected List<String> photo;

        /**
         * Gets the value of the photo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the photo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPhoto().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPhoto() {
            if (photo == null) {
                photo = new ArrayList<String>();
            }
            return this.photo;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tag"
    })
    public static class Tags {

        @XmlElement(name = "Tag", required = true)
        protected List<String> tag;

        /**
         * Gets the value of the tag property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the tag property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTag().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTag() {
            if (tag == null) {
                tag = new ArrayList<String>();
            }
            return this.tag;
        }

    }

}
